# Generated by Django 5.2.3 on 2025-07-28 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kategori Adı")),
                (
                    "slug",
                    models.CharField(
                        blank=True, unique=True, verbose_name="URL Dostu İsim"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şehir Adı")),
                (
                    "slug",
                    models.CharField(
                        blank=True, unique=True, verbose_name="URL Dostu İsim"
                    ),
                ),
            ],
            options={
                "verbose_name": "Şehir",
                "verbose_name_plural": "Şehirler",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Yer Adı")),
                (
                    "slug",
                    models.CharField(
                        blank=True, unique=True, verbose_name="URL Dostu İsim"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Hakkında"),
                ),
                (
                    "lont",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Enlem",
                    ),
                ),
                (
                    "long",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Boylam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yer",
                "verbose_name_plural": "Yerleşimler",
            },
        ),
        migrations.CreateModel(
            name="Township",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="İlçe Adı")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="URL Dostu İsim"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.city",
                        verbose_name="Şehir",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlçe",
                "verbose_name_plural": "İlçeler",
                "unique_together": {("slug", "city")},
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Etkinlik Adı")),
                (
                    "slug",
                    models.CharField(
                        blank=True, unique=True, verbose_name="URL Dostu İsim"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="Etkinlik URL'i",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="İçerik"),
                ),
                (
                    "img_url",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="Görsel URL'i",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="Ücretsiz Mi?"),
                ),
                (
                    "ticket_url",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="Bilet URL'i",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayınlandı mı?"),
                ),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizatör",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.location",
                        verbose_name="Yer",
                    ),
                ),
                (
                    "township",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.township",
                        verbose_name="İlçe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etkinlik",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.activity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "activity")},
            },
        ),
    ]
