# Generated by Django 5.2.3 on 2025-07-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.category"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="img_url",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.location"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="ticket_url",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="township",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.township"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="url",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="township",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.city"
            ),
        ),
        migrations.AlterField(
            model_name="township",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
