# Generated by Django 5.2.3 on 2025-07-15 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Etkinlik",
                "verbose_name_plural": "Etkinlikler",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Şehir", "verbose_name_plural": "Şehirler"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Yer", "verbose_name_plural": "Yerleşimler"},
        ),
        migrations.AlterModelOptions(
            name="township",
            options={"verbose_name": "İlçe", "verbose_name_plural": "İlçeler"},
        ),
        migrations.AddField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Oluşturulma Tarihi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizatör",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="İçerik"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bitiş Tarihi/Saati"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="img_url",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Görsel URL'i"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="Ücretsiz Mi?"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.location",
                verbose_name="Yer",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Etkinlik Adı"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="slug",
            field=models.CharField(
                blank=True, unique=True, verbose_name="URL Dostu İsim"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Başlangıç Tarihi/Saati"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="ticket_url",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Bilet URL'i"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="township",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.township",
                verbose_name="İlçe",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="url",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Etkinlik URL'i"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Kategori Adı"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                blank=True, unique=True, verbose_name="URL Dostu İsim"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Şehir Adı"),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.CharField(
                blank=True, unique=True, verbose_name="URL Dostu İsim"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Hakkında"),
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Boylam",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="lont",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Enlem",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Yer Adı"),
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.CharField(
                blank=True, unique=True, verbose_name="URL Dostu İsim"
            ),
        ),
        migrations.AlterField(
            model_name="township",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.city",
                verbose_name="Şehir",
            ),
        ),
        migrations.AlterField(
            model_name="township",
            name="name",
            field=models.CharField(max_length=200, verbose_name="İlçe Adı"),
        ),
        migrations.AlterField(
            model_name="township",
            name="slug",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="URL Dostu İsim"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="township",
            unique_together={("slug", "city")},
        ),
    ]
