# Generated by Django 5.2.3 on 2025-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_activity_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Yayınlandı mı?"),
        ),
    ]
