# Generated by Django 5.2.3 on 2025-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_activity_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Yayınlandı mı?"),
        ),
    ]
