# Generated by Django 5.2.4 on 2025-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_location_long_alter_location_lont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
