# Generated by Django 5.2.4 on 2025-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_location_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='slug',
            field=models.CharField(max_length=128),
        ),
    ]
