# Generated by Django 5.2.3 on 2025-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_activity_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bitiş Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Başlangıç Tarihi"
            ),
        ),
    ]
