# Generated by Django 5.2.3 on 2025-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_township_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
