# Generated by Django 5.2.3 on 2025-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
