# Generated by Django 5.2.3 on 2025-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_activity_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
