# Generated by Django 5.2.3 on 2025-07-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_alter_activity_ticket_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["start_date"], "verbose_name": "Etkinlik"},
        ),
    ]
